#!/bin/bash
# =============================================================================
# Generate .devcontainer/.env from:
#   - the host's UID/GID (for non-root container user matching)
#   - the project name extracted from <repo>/pixi.toml (SSoT)
#   - the default values declared below
#
# - VS Code devcontainer:  runs automatically via initializeCommand
# - CLI (standalone):       run once with `bash .devcontainer/init-env.sh`
#
# An existing .devcontainer/.env is never overwritten — delete it to regenerate.
# =============================================================================
set -e

# -----------------------------------------------------------------------------
# Default values for container-startup scalars (the SSoT for these defaults).
# Override per-invocation by exporting the variable before running this script:
#     CUDA_VERSION=12.6.0 LOCALE=ja_JP.UTF-8 bash .devcontainer/init-env.sh
# Or edit the generated .devcontainer/.env after the fact.
# -----------------------------------------------------------------------------
DEFAULT_CUDA_VERSION="12.8.0"             # base image CUDA tag
DEFAULT_UBUNTU_VERSION="24.04"            # base image Ubuntu tag (nvidia/cuda:<cuda>-devel-ubuntu<ubuntu>)
DEFAULT_WORKSPACE_DIR="/workspace"        # workspace mount point inside container
DEFAULT_DEFAULT_USER="developer"          # non-root user name inside container
DEFAULT_LOCALE="en_US.UTF-8"              # LANG / LC_ALL / locale-gen target
DEFAULT_DISPLAY_NUM=":1"                  # X11 display number for GUI forwarding
DEFAULT_NVIDIA_VISIBLE_DEVICES="all"      # GPU visibility (indices or "all")

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PIXI_TOML="${REPO_ROOT}/pixi.toml"
ENV_FILE="${SCRIPT_DIR}/.env"

# ----- Extract project name from pixi.toml (the SSoT) ------------------------
# Looks under [workspace] first (pixi >= 0.41 canonical name), then falls back
# to the deprecated [project] table for older pixi.toml files.
# Prefer Python's tomllib (3.11+) for correctness; fall back to an awk-based
# parse so the script also works on hosts without Python 3.11.
extract_project_name() {
    if command -v python3 >/dev/null 2>&1 && \
       python3 -c "import tomllib" 2>/dev/null; then
        python3 -c "
import tomllib, sys
with open('${PIXI_TOML}', 'rb') as f:
    data = tomllib.load(f)
table = data.get('workspace') or data.get('project') or {}
name = table.get('name')
if not name:
    sys.exit(1)
print(name)
"
    else
        # awk fallback: match [workspace] or [project] table, return first
        # `name = \"...\"` found under either.
        awk '
            /^\[(workspace|project)\]/ { in_table = 1; next }
            /^\[/                       { in_table = 0 }
            in_table && /^[[:space:]]*name[[:space:]]*=/ {
                sub(/^[^"]*"/, "")
                sub(/".*$/, "")
                print
                exit
            }
        ' "${PIXI_TOML}"
    fi
}

if [ ! -f "${PIXI_TOML}" ]; then
    echo "[init-env] ERROR: ${PIXI_TOML} not found." >&2
    echo "[init-env] pixi.toml is the SSoT for the project name; create it first." >&2
    exit 1
fi

PROJECT_NAME="$(extract_project_name)"
if [ -z "${PROJECT_NAME}" ]; then
    echo "[init-env] ERROR: could not extract [workspace].name (or [project].name) from ${PIXI_TOML}." >&2
    exit 1
fi

# ----- Generate .devcontainer/.env (only if absent) --------------------------
if [ -f "${ENV_FILE}" ]; then
    echo "[init-env] ${ENV_FILE} already exists; leaving untouched (project=${PROJECT_NAME})"
    exit 0
fi

HOST_UID="$(id -u)"
HOST_GID="$(id -g)"

if [ "${HOST_UID}" = "0" ] || [ "${HOST_GID}" = "0" ]; then
    echo "[init-env] ERROR: do not run as root (got UID=${HOST_UID}, GID=${HOST_GID})." >&2
    echo "[init-env] Re-run as a regular user so the container user matches host file ownership." >&2
    if [ -n "${SUDO_USER:-}" ]; then
        echo "[init-env] hint: re-run without sudo (your real user is '${SUDO_USER}')." >&2
    fi
    exit 1
fi

# Resolve each variable: caller-exported value wins, else the default declared
# at the top of this script.
cat > "${ENV_FILE}" <<EOF
# =============================================================================
# Auto-generated by .devcontainer/init-env.sh from <repo>/pixi.toml + host.
# Edit values to override defaults; delete this file and re-run init-env.sh
# to regenerate (e.g. after renaming the project in pixi.toml).
# Defaults live at the top of init-env.sh.
# =============================================================================

# --- Identity (derived: pixi.toml [workspace].name + host id) ---
COMPOSE_PROJECT_NAME=${PROJECT_NAME}
HOST_UID=${HOST_UID}
HOST_GID=${HOST_GID}

# --- Container-startup scalars (defaults; override as needed) ---
CUDA_VERSION=${CUDA_VERSION:-${DEFAULT_CUDA_VERSION}}
UBUNTU_VERSION=${UBUNTU_VERSION:-${DEFAULT_UBUNTU_VERSION}}
WORKSPACE_DIR=${WORKSPACE_DIR:-${DEFAULT_WORKSPACE_DIR}}
DEFAULT_USER=${DEFAULT_USER:-${DEFAULT_DEFAULT_USER}}
LOCALE=${LOCALE:-${DEFAULT_LOCALE}}
DISPLAY_NUM=${DISPLAY:-${DEFAULT_DISPLAY_NUM}}
NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-${DEFAULT_NVIDIA_VISIBLE_DEVICES}}
EOF

echo "[init-env] generated ${ENV_FILE}  (project=${PROJECT_NAME}, UID=${HOST_UID}, GID=${HOST_GID})"
